---
title: "Travail de session BOT500 - Une abondance d’oiseaux du Nord au Sud du Québec"
author:
  - name: "Frédérick St-Pierre"
    affiliation: "stpf2507"
  - name: "Yohan Wegener"
    affiliation: "wegy1101"
  - name: "Félix Labbé"
    affiliation: "labfXXXX"
  - name: "Aurel Veillet"
    affiliation: "veiaXXXX"

Résumé: |
  This study investigates the abundance of birds from Northern to Southern Quebec. We analyze the distribution patterns of various bird species and assess their diversity across different ecological regions. Our findings highlight the importance of conservation efforts in preserving avian biodiversity in Quebec.

Significance: |
  Ce travail a été réalisé dans le cadre du cours BOT500 par des étudiants au BAC en écologie.

keywords:
  - Diversité
  - Paruline
  - Québec

pnas_type: pnasresearcharticle
bibliography: pnas-sample.bib
csl: pnas.csl
lineno: false

output:
  pdf_document:
    toc: true
  pnas_article:
    lineno: false
---

###INTRODUCTION

Afin de comprendre la dynamique de la biodiversité aviaire du Québec sur une période donnée, nous avons établi une question générale composée deux sous-questions nous permettant d’y parvenir : Y a-t-il une corrélation entre la richesse spécifique et l’abondance des espèces d’oiseaux au Québec? 
1-	Quelle est la tendance de la richesse aviaire spécifique du Québec de 2016 à 2020 ? 
2-	Quelle est la tendance d'abondance selon la latitude?
La première question cherche à établir s'il existe une corrélation entre la richesse spécifique (le nombre total d'espèces) et l'abondance (la quantité relative de chaque espèce). Comprendre cette relation est crucial pour évaluer la santé globale d'un écosystème et comment il pourrait être affecté par des changements environnementaux.
La deuxième question cherche à analyser la tendance de la richesse aviaire spécifique dans la région du Québec au cours des années 2016 à 2020. Cette analyse temporelle permettrait de détecter des changements survenus dans la diversité des espèces aviaires au fil du temps, ce qui pourrait être lié à des facteurs tels que le changement climatique, la dégradation de l'habitat ou d'autres pressions environnementales.
Enfin, la troisième question explore la variabilité saisonnière de la richesse aviaire spécifique. La diversité des espèces aviaires varie tout au long de l'année à la suite des changements de saison. Les résultats peuvent fournir des informations importantes sur les schémas de migration, les cycles de reproduction et les fluctuations des populations, ce qui est crucial pour la conservation et la gestion des écosystèmes. En somme, ces questions cherchent à éclairer les liens complexes entre la biodiversité aviaire, le temps et l'environnement dans la région du Québec.

###MÉTHODE

Les données utilisées dans ce travail représentent la composition et la phénologie sonore des oiseaux au Québec, recueillies dans le cadre d'un programme de surveillance de la biodiversité acoustique mené par le ministère de l’Environnement, de la Lutte contre les Changements Climatiques, de la Faune et des Parcs (MELCCFP), dans le contexte du Réseau de suivi de la biodiversité du Québec. Elles répertorient les observations sonores des oiseaux. Les inventaires acoustiques sont réalisés au moyen d'enregistreurs sonores qui capturent les cris et les chants des oiseaux. Ces enregistrements représentent des efforts d'échantillonnage et sont ensuite analysés par un spécialiste en taxonomie qui identifie les espèces d'oiseaux enregistrées. Lorsque possible, l'heure de l'observation est également enregistrée (time_obs). Ainsi, ces données ont été analysées grâce au logiciel R afin de créer des figures qui représentent les résultats correspondant aux trois questions énoncées ci-dessus.

###RÉSULTATS

À la suite de la création d’une base de données et des analyses dans RStudio, trois figures ont été créées afin de mieux répondre à nos questions.
La figure 1 présente le nombre d’espèce présente en fonction de la latitude du Québec. La régression en bleue permet de voir la moyenne d’espèce unique. Les points présents dans la figure représentent chaque station d’écoute. 
La figure 2 présente l’abondance des observations de parulines, elle aussi en fonction de la latitude. Une régression, en bleue, avec l’incertitude, en gris, est observable. 
La figure 3 présente le nombre d’espèces uniques observées dans tous les sites d’échantillonnages de l’étude pour chaque année, de 2016 à 2020.
